### ISSUE TITLE
专业术语请教

### ISSUE THREAD

**Issue by tfwang08** [GeorgeDu/vision-based-robotic-grasping#10]
杜博士，您好：
  请问为什么6D pose estimation要叫做estimation，而不是检测之类的？
谢谢

**Comment by GeorgeDu** [comment]
@tfwang96 您好，个人觉得检测器更关注检测出目标物体的能力，常用的度量包括IOU等，而6D位姿更强调估计的物体位姿的精度，一般假定输入数据中存在目标物体，常用的度量包括ADD、ADD-S、5°5cm等

**Comment by tfwang08** [comment]
感谢您的回复，我明白了。
