### ISSUE TITLE
如何制作自己的6d pose estimation训练数据集呢？

### ISSUE THREAD

**Issue by hlcool** [GeorgeDu/vision-based-robotic-grasping#12]
杜博好，目前做已知物体3D模型的抓取时，需要做6d pose estimation获得Rt变换矩阵。
如果采用深度学习的方法去做，需要大量标注好的训练数据，训练数据一般包括，3D mesh，RGB，depth，pose，mask等等，目前也有不少开源的数据，有linemod、ycb-video等等这些，也有一个[BOP: Benchmark for 6D Object Pose Estimation](https://bop.felk.cvut.cz/datasets/)的网站总结罗列并统一数据集的格式。但是这些开源数据集跑跑别人论文的demo是可以的。
假如我们想自己搜集一些待抓取物体，这些物体可以通过EinScan-SP桌面扫描仪获得物体的3D模型，那该如何制作一个和linemod或者ycb-video相似的数据集用来训练呢？有推荐比较好用的制作数据或者标注pose数据的工具吗？
我找到了[LabelFusion](https://github.com/RobotLocomotion/LabelFusion)、[ObjectDatasetTools](https://github.com/F2Wang/ObjectDatasetTools)这两个工具，但ObjectDatasetTools这个觉得标注的精度不高，LabelFusion的过程复杂。
也尝试过NVIDIA的[DOPE](https://github.com/NVlabs/Deep_Object_Pose)算法使用的NDDS+UE4工具，这个更复杂一些。
杜博训练6d pose estimation算法抓取自己的物体时，是怎么制作或者标注训练集的呢？
期待杜博的回复和指导，感谢感谢

**Comment by GeorgeDu** [comment]
@hlcool 惊涛你好，制作自己的训练集确实是痛点，之前用LabelFusion采集过数据集做过一些尝试，确实采集过程复杂一些，不过感觉没有太好的办法；训练集应该是需要虚拟数据集和真实数据集，因为只使用采集的真实数据集工作量太大；虚拟部分：需要重建带纹理逼真的3D模型，并且进行真实感的渲染，可以使用引擎；真实部分：可以借助LabelFusion采集一些，或者借助Aruco工具；个人觉得如果物体能够采集到深度数据，就可以不用单目6D位姿估计，可以使用基于点云的物体6D位姿估计或者配准算法；如果物体不能够采集到深度数据，那么才必须用单目6D位姿估计的方法；

**Comment by hlcool** [comment]
是的，谢谢杜博，制作数据集这个过程我确实走了不少弯路，试了很多种方法。
正如杜博所说，假如有深度数据，我们靠单视角的深度图恢复点云后跟3D模型进行ICP匹配也可以获得物体的位姿，LabelFusion就是用的这种思路，并且这个位姿是可以作为训练数据的真值的。
可是这种方法耗时太长，算法效率不高，假如我们想做动态的抓取、视觉伺服或者AR，这种方法就行不通。
针对有纹理的物体，目前我试过最好的方法就是[simtrack](https://github.com/karlpauwels/simtrack)和[MOPED](https://github.com/personalrobotics/moped)，不过他们是靠特征点匹配来做的。
杜博目前觉得使用深度学习方法（depth+rgb）做位姿估计精度比较高、实时性好的有哪些？ [PVN3D](https://github.com/ethnhe/PVN3D)咋样？

**Comment by GeorgeDu** [comment]
@hlcool 如果对速度有要求，确实需要用RGB来做；PVN3D很好，不过要求物体能够采集到深度图，而且2D分割效果较好；精度和速度都好比较难，不过可以参考下Google的MediaPipe Objectron，可以在移动端实时，但精度应该不能用于机器人抓取；感觉如果要落地，还是需要针对具体落地场景，优化算法以及端侧加速；

**Comment by hlcool** [comment]
谢谢杜博，我把这个issues先关闭，我昨天周末在家没事翻到你在智东西的公开课。ppt最后有你的微信二维码，希望能加你好友，以后有问题可以向你请教，3Q
