### ISSUE TITLE
关于6D位姿估计与抓取的问题

### ISSUE THREAD

**Issue by QiuJunning** [GeorgeDu/vision-based-robotic-grasping#15]
您好，
  非常感谢您共享的资料，我看到资料中有许多基于模型的位姿估计方法，但以我的理解是得到物体位姿后还需要根据位姿去选择抓取点，我想咨询下您从得到目标位姿到估计抓取点这一步我应该怎么做或者这属于什么问题？期望得到您的回答，谢谢！

**Comment by GeorgeDu** [comment]
> 

您好，抓取位姿需要预先定义好，也即在物体坐标系下夹爪的目标位姿；计算得到物体的位姿后，就可以应用同样变换得到夹爪的位姿；

**Comment by QiuJunning** [comment]
> 

感谢您的回复！不过我还是有些疑问，我该如何预定义物体坐标系下夹爪的目标位姿呢？这一步有没有相关的方向或者文献提供理论指导？

**Comment by GeorgeDu** [comment]
> 

可以参考GraspIt!哈
