### ISSUE TITLE
低成本硬件环境下的机械臂抓取

### ISSUE THREAD

**Issue by Whisht** [GeorgeDu/vision-based-robotic-grasping#17]
杜博士，您好。跟踪了您的综述文章及相关报告，自己此外阅读了一些CVPR2022等会议的新文章，我发现目前大多数的模型都是进行实例级别的位姿估计，需要对 CAD 模型和点云数据进行处理，对于计算资源的开销比较大。想向您请教一下，在计算资源有限有限的条件下，关于目标物体的 6DoF抓取 有没有什么好的建议，比如 [Jetson Nano](https://developer.nvidia.com/embedded/jetson-nano-developer-kit) 的开发套件。

目前我的想法是基于 RGBD 数据采用 3D 目标检测的网络生成物体的 bounding box，再恢复到相机坐标系下，而不是直接计算 $[R|t]$矩阵。
此外对于一些形状纹理比较规则的物体，如水杯（圆柱体），直接根据深度图匹配形状，同时搭配 2d 的目标检测获取类别信息；之后再进行变换到相机坐标系进行抓取。

请问您在处理这种目标物体比较简单的 6DoF 抓取任务时，有什么计算开销比较小的方式呢？谢谢。

**Comment by GeorgeDu** [comment]
@Whisht 您好，说一下我的理解哈：
“使用3D检测网络”：3D检测得到的是平面内的1D朝向，需要进行重力方向校正；物体要求根据包围盒能被抓取；好处是3D检测具有泛化性，能够适用一类物体；需要验证算法在端上的资源消耗和耗时；
“圆柱体根据深度图匹配形状”：需要已有物体3D点云，和物体的部分点云进行特征匹配，即全局配准；这个算法的耗时也需要统计；
建议可以多测试，初级版本可以直接使用检测/分割得到物体的单视角点云，直接计算点云的平均值，去抓取试试，看成功率多大；进一步，可以用全局配准的方法，或者一些其他配准的技巧，得到6D位姿；如果想泛化，也可以尝试使用3D检测算法；另外点云数目要简化，因为要获取位姿不需要稠密点云；

**Comment by Whisht** [comment]
> @Whisht 您好，说一下我的理解哈： “使用3D检测网络”：3D检测得到的是平面内的1D朝向，需要进行重力方向校正；物体要求根据包围盒能被抓取；好处是3D检测具有泛化性，能够适用一类物体；需要验证算法在端上的资源消耗和耗时； “圆柱体根据深度图匹配形状”：需要已有物体3D点云，和物体的部分点云进行特征匹配，即全局配准；这个算法的耗时也需要统计； 建议可以多测试，初级版本可以直接使用检测/分割得到物体的单视角点云，直接计算点云的平均值，去抓取试试，看成功率多大；进一步，可以用全局配准的方法，或者一些其他配准的技巧，得到6D位姿；如果想泛化，也可以尝试使用3D检测算法；另外点云数目要简化，因为要获取位姿不需要稠密点云；

感谢杜博士的回复，我先根据您的建议多尝试几个方法试试看。
