### ISSUE TITLE
关于专业名词的请教

### ISSUE THREAD

**Issue by songzhuozhu** [GeorgeDu/vision-based-robotic-grasping#8]
杜博士您好，我是一名研一的新生，对机器人的二维平面抓取这个方向很感兴趣。在读您的这篇论文时，对其中的一些专业名词不太了解，比如 antipodal robotic grasping的antipodal，grasp affordances和robotic affordances的affordances。这两个单词应该如何翻译，又该如何理解呢？谢谢。

**Comment by GeorgeDu** [comment]
> 在读您的这篇论文时，对其中的一些专业名词不太了解，比如 antipodal robotic grasping的antipodal，grasp affordances和robotic affordances的affordances。这两个单词应该如何翻译，又该如何理解呢？谢谢。

您好，Antipodal points可以翻译成对点，是指按照这一对点去抓能够抵抗外力将物体抓取；Grasp Affordance可以翻译成抓取可供性，Grasp affordance determines the object-hand relative configurations which lead to successful grasps. 可以理解为对物体上的某个区域进行抓取行为，抓取成功的概率吧
