### ISSUE TITLE
6D位姿估计和3D 目标检测之间的主要区别？

### ISSUE THREAD

**Issue by hlcool** [GeorgeDu/vision-based-robotic-grasping#9]
杜博士，您好：
跟踪阅读了你的两个github上的一些文章，想请教一下6D位姿估计和3D目标检测之间的主要区别是什么？
1、instance-level还比较好理解，因为有已知的3D模型，但对于category-level的位姿估计，感觉是和3D目标检测很相近，都可以得到3D包围盒，它俩的差别主要在哪里呢？
2、还有一个是评价指标ADD_S，看计算公式，要求已知物体的3D点云才能计算，对于category-level的位姿估计，因为3D模型是未知的，你如何利用ADD_S进行计算呢？
辛苦杜博能给予指点，谢谢

**Comment by GeorgeDu** [comment]
您好，说下我的个人理解哈：一个物体具有的空间属性主要有：3D平移(3D translation: x, y, z)，3D旋转(3D Rotation: \alpha, \beta, \gamm)，3D尺寸(3D Size: length, width, height)。其中3D平移T和3D旋转R是相对的概念，也即[RT]是将物体由初始状态变换到当前状态的变换；3D尺度是一个绝对的概念，每个物体都有唯一的3DSize。
3D检测、6D位姿估计都可以统称为Object Pose Estimation，区别在于各自需要估计参数的不同。3D检测估计的是物体的3D平移+1D角度+3D尺寸，其中1D角度是将3D旋转简化为单个平面内的旋转角度；6D位姿估计的是物体的3D平移+3D旋转，由于6D位姿估计针对的是实例级别的物体，因此其3D尺寸相当于已知；类别级6D位姿估计的是3D平移+3D旋转+3D尺寸，可以认为是任意旋转的3D检测。
类别级物体6D位姿的评价指标，论文NOCS中使用了3D检测的度量以及6D位姿估计的度量，3D检测计算不同3D IoU下的AP，6D位姿估计使用3D平移小于m cm的AP，3D角度小于n度下的AP，可以看下论文哈。

**Comment by GeorgeDu** [comment]
您好，说下我的个人理解哈：一个物体具有的空间属性主要有：3D平移(3D translation: x, y, z)，3D旋转(3D Rotation: \alpha, \beta, \gamm)，3D尺寸(3D Size: length, width, height)。其中3D平移T和3D旋转R是相对的概念，也即[RT]是将物体由初始状态变换到当前状态的变换；3D尺度是一个绝对的概念，每个物体都有唯一的3DSize。
3D检测、6D位姿估计都可以统称为Object Pose Estimation，区别在于各自需要估计参数的不同。3D检测估计的是物体的3D平移+1D角度+3D尺寸，其中1D角度是将3D旋转简化为单个平面内的旋转角度；6D位姿估计的是物体的3D平移+3D旋转，由于6D位姿估计针对的是实例级别的物体，因此其3D尺寸相当于已知；类别级6D位姿估计的是3D平移+3D旋转+3D尺寸，可以认为是任意旋转的3D检测。
类别级物体6D位姿的评价指标，论文NOCS中使用了3D检测的度量以及6D位姿估计的度量，3D检测计算不同3D IoU下的AP，6D位姿估计使用3D平移小于m cm的AP，3D角度小于n度下的AP，可以看下论文哈。
